apiVersion: v1
data:
  CODERUNTIME_DATABASE_NAME: coderuntime
  CODERUNTIME_DATABASE_PORT: '3306'
  CODERUNTIME_DATABASE_SSL_MODE: skip-verify
  CODERUNTIME_LOG_FORMAT: json
  CODERUNTIME_LOG_LEVEL: info
  CODERUNTIME_QUEUE_PROVIDER: sqs
  CODERUNTIME_REDIS_PORT: '6379'
  CODERUNTIME_REDIS_TLS_ENABLED: 'false'
  CODERUNTIME_SQS_DLQ_QUEUE_URL: ''
  CODERUNTIME_SQS_JOBS_QUEUE_URL: https://sqs.ap-southeast-2.amazonaws.com/768054003064/code-submission-processing-queue
  CODERUNTIME_SQS_MAX_CONCURRENCY: '3'
  CODERUNTIME_SQS_PRIORITY_QUEUE_URL: ''
  CODERUNTIME_SQS_REGION: ap-southeast-2
  CODERUNTIME_SQS_START_QUEUE_URL: https://sqs.ap-southeast-2.amazonaws.com/768054003064/code-submission-completed-queue
  CODERUNTIME_SQS_VISIBILITY_TIMEOUT: '330'
  CODERUNTIME_SQS_WAIT_TIME_SECONDS: '20'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: shared
    app.kubernetes.io/name: coderuntime
  name: common-config
  namespace: coderuntime
---
apiVersion: v1
data:
  CODERUNTIME_CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
  CODERUNTIME_CORS_ALLOWED_ORIGINS: https://app.coderuntime.io
  CODERUNTIME_CORS_MAX_AGE: '86400'
  CODERUNTIME_DATABASE_CONN_MAX_LIFETIME: 300s
  CODERUNTIME_DATABASE_MAX_IDLE_CONNS: '10'
  CODERUNTIME_DATABASE_MAX_OPEN_CONNS: '50'
  CODERUNTIME_JWT_ACCESS_TOKEN_EXP: 24h
  CODERUNTIME_METRICS_ENABLED: 'true'
  CODERUNTIME_RATE_LIMIT_AUTH_LIMIT: '60'
  CODERUNTIME_RATE_LIMIT_AUTH_PERIOD: 60s
  CODERUNTIME_RATE_LIMIT_ENABLED: 'false'
  CODERUNTIME_RATE_LIMIT_LIMIT: '200'
  CODERUNTIME_RATE_LIMIT_PERIOD: 60s
  CODERUNTIME_RATE_LIMIT_READ_LIMIT: '10000'
  CODERUNTIME_RATE_LIMIT_READ_PERIOD: 60s
  CODERUNTIME_RATE_LIMIT_TRUSTED_API_KEYS: ''
  CODERUNTIME_RATE_LIMIT_WRITE_LIMIT: '10000'
  CODERUNTIME_RATE_LIMIT_WRITE_PERIOD: 60s
  CODERUNTIME_REDIS_DB: '0'
  CODERUNTIME_SERVER_IDLE_TIMEOUT: 150s
  CODERUNTIME_SERVER_PORT: '8002'
  CODERUNTIME_SERVER_READ_TIMEOUT: 30s
  CODERUNTIME_SERVER_WRITE_TIMEOUT: 150s
  CODERUNTIME_TRACING_SERVICE_NAME: api-gateway
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: api-gateway
  name: api-config
  namespace: coderuntime
---
apiVersion: v1
data:
  CODERUNTIME_DATABASE_CONN_MAX_LIFETIME: 300s
  CODERUNTIME_DATABASE_MAX_IDLE_CONNS: '1'
  CODERUNTIME_DATABASE_MAX_OPEN_CONNS: '3'
  CODERUNTIME_DOCKER_CONTAINER_TIMEOUT: 30s
  CODERUNTIME_DOCKER_NETWORK_MODE: none
  CODERUNTIME_TRACING_SERVICE_NAME: worker
  CODERUNTIME_WORKER_CONCURRENCY: '3'
  CODERUNTIME_WORKER_COUNT: '3'
  CODERUNTIME_WORKER_JOB_TIMEOUT: 30s
  CODERUNTIME_WORKER_TMP_DIR: /tmp/sandbox
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/name: worker
  name: worker-config
  namespace: coderuntime

