{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coderuntime.serviceAccountName" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coderuntime.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
automountServiceAccountToken: false
{{- end }}

{{- if .Values.worker.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coderuntime.serviceAccountName" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coderuntime.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
{{- end }}
